#!/bin/bash
# Modded Minecraft launch script - generated by the Modded Minecraft AMP template update stages.
# Usage: start-modded.sh <initialMemMB> <maxMemMB> <javaVersion|auto> <acceptEula>
cd "$(dirname "$0")" || exit 1
IM="${1:-2048}"
XM="${2:-6144}"
JV="${3:-auto}"
EULA="${4:-false}"
LOG=".last-launch.log"
CACHE=".java-version"

if [ "$EULA" != "true" ] && [ "$EULA" != "True" ]; then
  echo "You must accept the Minecraft EULA before the server can start."
  echo "Tick 'Accept Minecraft EULA' under Configuration > Java and Memory, then start again."
  exit 1
fi
echo "eula=true" > eula.txt

# Download a Temurin JRE on demand. Any version the pack turns out to need can be
# fetched here, so the server is not limited to the versions offered in the UI.
ensure_jre() {
  v="$1"
  [ -x "jre/$v/bin/java" ] && return 0
  arch=x64; case "$(uname -m)" in aarch64|arm64) arch=aarch64;; esac
  echo "Downloading Temurin JRE $v ..."
  mkdir -p "jre/$v" || return 1
  if ! wget -qO "jre$v.tgz" "https://api.adoptium.net/v3/binary/latest/$v/ga/linux/$arch/jre/hotspot/normal/eclipse"; then
    echo "ERROR: could not download Java $v (no such release for this platform?)"
    rm -f "jre$v.tgz"; rmdir "jre/$v" 2>/dev/null; return 1
  fi
  tar -xzf "jre$v.tgz" -C "jre/$v" --strip-components=1 && rm -f "jre$v.tgz"
  [ -x "jre/$v/bin/java" ]
}

# Resolve the starting Java version: an explicit choice wins, otherwise reuse
# whatever was detected last time, otherwise start at 21.
case "$JV" in
  ''|auto|Auto|AUTO)
    if [ -s "$CACHE" ]; then read -r JV < "$CACHE"; else JV=21; fi
    ;;
esac
case "$JV" in ''|*[!0-9]*) JV=21;; esac

SERVER=""
[ -f .install-results.env ] && . ./.install-results.env
if [ -z "$SERVER" ] || { [ ! -f "$SERVER" ] && [ ! -f "${SERVER##*/}" ]; }; then
  for f in run.sh start.sh startserver.sh fabric-server-launch.jar quilt-server-launch.jar server.jar; do
    if [ -f "$f" ]; then SERVER="$PWD/$f"; break; fi
  done
fi
if [ -z "$SERVER" ]; then
  echo "No server entry point found. Set the modpack URL and API key in Configuration > Modpack, then click Update."
  exit 1
fi
if [ ! -f "$SERVER" ] && [ -f "${SERVER##*/}" ]; then
  SERVER="$PWD/${SERVER##*/}"
fi

attempt=0
while [ "$attempt" -lt 4 ]; do
  attempt=$((attempt + 1))
  if ! ensure_jre "$JV"; then
    echo "Falling back to the system Java installation."
  else
    export JAVA_HOME="$PWD/jre/$JV"
    export PATH="$JAVA_HOME/bin:$PATH"
  fi

  echo "Launching $(basename "$SERVER") with Java $JV (${IM}MB - ${XM}MB)"
  : > "$LOG"
  case "$SERVER" in
    *.sh)
      printf "%s\n" "-Xms${IM}M" "-Xmx${XM}M" > user_jvm_args.txt
      chmod +x "$SERVER" 2>/dev/null
      bash "$SERVER" nogui 2>&1 | tee -a "$LOG"
      ;;
    *)
      java "-Xms${IM}M" "-Xmx${XM}M" -jar "$SERVER" nogui 2>&1 | tee -a "$LOG"
      ;;
  esac
  rc="${PIPESTATUS[0]}"

  # A modpack's mod loader may be built for a newer Java than we guessed. The JVM
  # reports the class file version it needs, so translate that into a Java release
  # (class file major version 44 + release), fetch it, and try again.
  need=""
  if grep -q "UnsupportedClassVersionError" "$LOG" 2>/dev/null; then
    cfv=$(grep -oE "class file version [0-9]+" "$LOG" | head -1 | grep -oE "[0-9]+")
    [ -n "$cfv" ] && need=$((cfv - 44))
  fi
  if [ -n "$need" ] && [ "$need" != "$JV" ] && [ "$need" -ge 8 ] && [ "$need" -le 30 ]; then
    echo "This modpack needs Java $need, not Java $JV - switching and retrying."
    JV="$need"
    echo "$JV" > "$CACHE"
    continue
  fi

  [ "$rc" = "0" ] && echo "$JV" > "$CACHE"
  exit "$rc"
done
echo "Giving up after $attempt attempts to find a working Java version."
exit 1
