#!/bin/bash
# Modded Minecraft launch script - generated by the Modded Minecraft AMP template update stages.
# Usage: start-modded.sh <initialMemMB> <maxMemMB> <javaVersion> <acceptEula>
cd "$(dirname "$0")" || exit 1
IM="${1:-2048}"
XM="${2:-6144}"
JV="${3:-17}"
EULA="${4:-false}"
if [ "$EULA" != "true" ] && [ "$EULA" != "True" ]; then
  echo "You must accept the Minecraft EULA before the server can start."
  echo "Tick 'Accept Minecraft EULA' under Configuration > Java and Memory, then start again."
  exit 1
fi
echo "eula=true" > eula.txt
if [ -x "jre/$JV/bin/java" ]; then
  export JAVA_HOME="$PWD/jre/$JV"
  export PATH="$JAVA_HOME/bin:$PATH"
else
  echo "WARNING: bundled Java $JV runtime not found, falling back to system java. Run Update to fix this."
fi
SERVER=""
[ -f .install-results.env ] && . ./.install-results.env
if [ -z "$SERVER" ] || { [ ! -f "$SERVER" ] && [ ! -f "${SERVER##*/}" ]; }; then
  for f in run.sh start.sh startserver.sh fabric-server-launch.jar quilt-server-launch.jar server.jar; do
    if [ -f "$f" ]; then SERVER="$PWD/$f"; break; fi
  done
fi
if [ -z "$SERVER" ]; then
  echo "No server entry point found. Set the modpack URL and API key in Configuration > Modpack, then click Update."
  exit 1
fi
if [ ! -f "$SERVER" ] && [ -f "${SERVER##*/}" ]; then
  SERVER="$PWD/${SERVER##*/}"
fi
echo "Launching $SERVER with Java $JV (${IM}MB - ${XM}MB)"
case "$SERVER" in
  *.sh)
    printf "%s\n" "-Xms${IM}M" "-Xmx${XM}M" > user_jvm_args.txt
    chmod +x "$SERVER" 2>/dev/null
    exec bash "$SERVER" nogui
    ;;
  *)
    exec java "-Xms${IM}M" "-Xmx${XM}M" -jar "$SERVER" nogui
    ;;
esac
